image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2  
  TAG: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - push

build_frontend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$TAG frontend/
  only:
    - main

build_backend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$TAG backend/
  only:
    - main

build_nginx:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/nginx:$TAG nginx/
  only:
    - main

push_frontend:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/frontend:$TAG
  only:
    - main

push_backend:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/backend:$TAG
  only:
    - main

push_nginx:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/nginx:$TAG
  only:
    - main

