stages:
  - build
  - test
  - deploy

build_frontend:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build

build_backend:
  stage: build
  image: python:3.9
  script:
    - cd /backend
    - pip install -r requirements.txt

build_nginx:
  stage: build
  image: nginx:latest
  script:
    - echo "Building nginx"
# test_job:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - merge_requests

# deploy_job:
#   stage: deploy
#   script:
#     - echo "Deploying the application"
#   only:
#     - main
#   when: manual
