image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build

build_backend:
  stage: build
  script:
    - apt-get update && apt-get install -y python3 python3-pip
    - cd backend
    - pip3 install -r requirements.txt
    - python -m unittest discover
  artifacts:
    paths:
      - backend/__pycache__/

build_nginx:
  stage: build
  script:
    - cd nginx
    - docker build -t my_nginx .

test_frontend:
  stage: test
  script:
    - cd frontend
    - npm test -- --watchAll=false

test_backend:
  stage: test
  script:
    - cd backend
    - python -m unittest discover

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
    # Добавьте здесь команды для развертывания, например, через SSH
