services:
  backend:
    build:
      context: ./backend
    restart: always
    networks:
      - etoapp
    ports:
      - "5001:5000"
  frontend:
    build:
      context: ./frontend
    restart: always
    networks:
      - etoapp
    ports:
      - "3001:3000"
    depends_on:
      - backend
  nginx:
    build:
      context: ./nginx
    restart: always
    networks:
      - etoapp
    ports:
      - "81:80"
    depends_on:
      - frontend
      - backend
networks:
  etoapp:
    driver: bridge
